### ISSUE TITLE
Feature Request: factor multiplier

### ISSUE THREAD

**Issue by Ceveloper** [DominikMuhle/latex-table-editor#5]
I  have a feature request: multiplying chosen metrics by a given factor.

The hydra configuration could  include another default rule called `coefficient`.:
```
default_rules:
  order: min
  highlighting: ["\\bfseries{%s}", "\\underline{%s}"]
  default: "%s"
  precision: "%.3f"
  coefficient: 100
```
Then the function highlight_extrema() in highlighting.py could forward this coefficient factor and execute the multiplication:
```
def highlight_extrema(
    data: str | float | int,
    extrema: list[float | int],
    highlights: str,
    default: str,
    precision: str = "%.3f",
    coefficient: float = 1.0, 
) -> str
```
 Thanks a lot for the amazing tool!
